// client/src/views/Login.vue
<template>
    <div>
        <form v-on:submit="doUserLogin">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input v-model="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input v-model="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn">Submit</button>
        </form>
    </div>
</template>

<script>
    // import { mapActions } from 'vuex';
    export default {
        data () {
            return {
                email: '',
                password: ''
            }
        },
        
        methods: {
            doUserLogin() {
                const user = {
                  strategy: 'local',  
                  email: this.email,
                  password: this.password
                }
                console.log(user)
                this.$store.dispatch('users/login', user)
            }
        }
    }
</script>

<style scoped>
.btn {
    background: #00ff00;
    color: white;
    font-weight: bold;
}

</style>

// ng-client/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  
  email: ''
  password: ''
  invalidForm: Boolean = false;

  constructor(private service: AuthService) { }

  ngOnInit(): void {
  }

  login() {
    const user = {
      strategy: 'local',
      email: this.email,
      password: this.password
    }
    if (user.email == null || user.email == undefined && user.password == null || user.password == undefined) {
      this.invalidForm = true;
    } else {
      this.service.doLogin(user).subscribe(res => {
        console.log(res);
      })
    }
  }

}

<app-invalid  *ngIf="invalidForm"></app-invalid>
<div class="container">
    <h1>Login</h1>
    <form  (submit)="login()">
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" [(ngModel)]="email" name="email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" [(ngModel)]="password" name="password">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
